In [1]:
# Swapping two numbers:
# using third variable, extra variable is needed.
# Using +- operations, the sum exceeds 8 and is 3 bits so we are wasting one bit
# Using xor no extra bit is wasted. Number of bits used in inputs and output are same.

a = 5
b = 6

temp = a
a = b
b = temp

a
b

5

In [2]:
a
b

5

In [3]:
a

6

In [4]:
b

5

In [5]:
a = 5 # 101
b = 6 # 110

a = a + b # 11 # 4bits
b = a - b # 5
a = a - b # 6

print(a)
print(b)

6
5


In [7]:
a = 5
b = 6

a = a ^ b 
b = a ^ b 
a = a ^ b

print(a)
print(b)

6
5


In [8]:
# unique to python:

a = 5
b = 6

a,b = b,a

print(a)
print(b)

6
5


In [9]:
# right side is solved first
# b , a goes into a stack and then it gets revered - concept of rotation - it will rotate these two values
# ROT_TWO() - Swaps the 2 top most stack elements

In [10]:
for i in range(5):
    if(i==3):
        break
    print("Hello",i)

Hello 0
Hello 1
Hello 2


In [11]:
for i in range(5):
    if(i==3):
        continue
    print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 4


In [1]:
for i in range(5):
    if(i==3):
        pass
    print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4


In [12]:
# eg for understanding the usage of pass keyword:

In [13]:
# def is used to define a function in python


In [15]:
def fun():
    print("do something")
    print("do something")
    print("do something")
    print("do something")
    
a = 5

In [16]:
# now let's say define the function later and I know the function name but idk what to put inside it. Maybe I will change or implement it later but as of now i just wanna define the function fun but idk the statements. In this case we say pass.

In [17]:
def fun():
    pass
    
a = 5

In [18]:
# like an empty block in other languages

In [19]:
# in any block we can use it. 

In [20]:
for i in range(5):
    if(i==3):
        continue
    print("Hello",i)
    if(i==4):
        pass # later maybe print("Hey")

Hello 0
Hello 1
Hello 2
Hello 4


In [21]:
class Human:
    pass # Later we may write variables and methods

In [22]:
# continue and break are normally used in a function or in a loop but pass is normally use it to skip the block when we don't know what to write in it atm

In [23]:
# for else - new thing in python:

In [24]:
nums = [12,15,18,21,26]
# we need to check if the above list has a number divisible by 5 and if we have it we just have to print it
for num in nums:
    if num % 5 == 0:
        print(num)

15


In [25]:
# If there are more than 1 number in the list div by 5 both will be printed but if we wanna print only the first number, so we will use break

In [27]:
nums = [12,15,18,21,25]
# we need to check if the above list has a number divisible by 5 and if we have it we just have to print it
for num in nums:
    if num % 5 == 0:
        print(num)
        break

15


In [28]:
nums = [12,15,18,21,25]
# we need to check if the above list has a number divisible by 5 and if we have it we just have to print it
for num in nums:
    if num % 5 == 0:
        print(num)
       

15
25


In [4]:
# If we have no num div by 5 we can use else and print does not exist
nums = [12,11,18,21,22]
# we need to check if the above list has a number divisible by 5 and if we have it we just have to print it
for num in nums:
    if num % 5 == 0:
        print(num)
        break
    else:
        print("Not found")

Not found
Not found
Not found
Not found
Not found


In [5]:
for num in nums:
    if num % 5 == 0:
        print(num)
        break
else: # This else is associated with the for loop and runs only if the entire loop is completed without break. This is because we don't wanna execute else at every iteration
    print("Not found")

Not found


In [31]:
# If we have a for loop and if we have a condition (if) in which there is a break, we can also use else with the for because this loop is never breaked

In [32]:
nums = [10,11,18,21,22]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
else: 
        print("Not found")

10


In [33]:
# break is compulsory in the for else

In [40]:
# Program to check if a number is prime or not:
num = 8
for i in range(2,num):
    if num % i == 0:
        print("Not Prime")
        break
else:
    print("Prime")

Not Prime


In [41]:
# Efficient Prime number checking see google like to run the loop till half or we can check for the sqrt

In [42]:
# Arrays:

In [43]:
# In arrays we have all the variables of the same type

In [44]:
# Arrays are similar to list but we need to have all the variables of the same type

In [1]:
# Arrays in python dont have specfic size/fixed size. We can expand and shrink the array easily. Methods are also there for assistance

In [6]:
# Arrays are used to store for eg marks of students in a class in a subject, instead of creating 100 variables, we can create an array.

In [8]:
import array as arr # arr is an alias for array

In [9]:
arr.array()

TypeError: array() takes at least 1 argument (0 given)

In [12]:
from array import * # Imports all or specify the functions you wanna work with

In [4]:
vals = array()

TypeError: array() takes at least 1 argument (0 given)

In [10]:
# 2 things to mention while creating the array: type of elements and the elements.
# here the keywords int,float etc do not work. Here we use type code.
# See table pic

In [13]:
vals = array('i',[5, 9, 8, 4, 2]) # Represent arrays using square brackets.

In [14]:
print(vals)

array('i', [5, 9, 8, 4, 2])


In [15]:
vals = array('i',[5, 9, 8.5, 4, 2])

TypeError: integer argument expected, got float

In [16]:
vals = array('i',[5, 9, -8, 4, 2])

In [17]:
print(vals)

array('i', [5, 9, -8, 4, 2])


In [18]:
vals = array('I',[5, 9, -8, 4, 2])

OverflowError: can't convert negative value to unsigned int

In [20]:
# Array helpful Function Examples:
print(vals.buffer_info())

(2720516265552, 5)


In [21]:
# The output above is a tuple with 2 values: 1st one is the address of the array and the 2nd one is the size of the array

In [22]:
print(vals.typecode)

i


In [24]:
# append and remove methods also to add and remove an element.
print(vals.reverse()) # reverse doesn't return a value

None


In [26]:
vals.reverse()
print(vals)

array('i', [5, 9, -8, 4, 2])


In [27]:
vals.reverse()
print(vals)

array('i', [2, 4, -8, 9, 5])


In [28]:
print(vals[0])

2


In [29]:
print(vals[1])

4


In [30]:
# above used to print single value and below can use any loop to print all the values one by one

In [31]:
# for loop makes sense when you know the range

In [32]:
for i in range(5):
    print(vals[i])

2
4
-8
9
5


In [33]:
# If we don't know the length and wanna make the array more dynamic:
for i in range(len(vals)): # len of vals will give the length and we pass that value in range and at runtime it'll be = 5
    print(vals[i])

2
4
-8
9
5


In [34]:
# Another way:
for i in vals: # here it'll directly go over the values as opposed to using for with range which will go for index values
    print(i)

2
4
-8
9
5


In [35]:
# for is very dynamic

In [36]:
# char array example:

In [38]:
vals = array('u',['a','e','i'])

In [39]:
for i in vals:
    print(i)

a
e
i


In [40]:
vals = array('I',[5, 9, 8, 4, 2])
# Creating a new array same as one created above. One way is the direct way by making a new variable and making a new array as above
# with the same type and values. But, sometimes idk the type or the values in the array and I wanna copy the array

In [42]:
newArray = array(vals.typecode,(a for a in vals)) # a represents one value at a time. It'll take one-one value from vals and assign it in the new array
for i in newArray:
    print(i)

5
9
8
4
2


In [43]:
# If I wanna assign square of the values of the old array in the new array:
newArray = array(vals.typecode,(a*a for a in vals))
for i in newArray:
    print(i)

25
81
64
16
4


In [44]:
# We can also use while loop above. But we manually have to initialise,check and inc or dec.

In [46]:
i = 0
while i < len(newArray):
    print(newArray[i])
    i += 1

25
81
64
16
4


In [47]:
# Making an array and taking values from the user:


In [49]:
vals = array('i',[]) # Creating an empty array
n = int(input("Enter the length of the array: "))
# while loop also can use but n known as for makes more sense:
for i in range(n):
    x = int(input("Enter next array element: "))
    vals.append(x)
print(vals)

Enter the length of the array: 3
Enter next array element: 55
Enter next array element: 9
Enter next array element: 6
array('i', [55, 9, 6])


In [51]:
vals = array('i',[]) # Creating an empty array
n = int(input("Enter the length of the array: "))
# while loop also can use but n known as for makes more sense:
for i in range(n):
     vals.append(int(input("Enter next array element: ")))
print(vals)

Enter the length of the array: 3
Enter next array element: 5
Enter next array element: 6
Enter next array element: 5
array('i', [5, 6, 5])


In [52]:
# searching array element manually and returning the index value.
ele = int(input("Enter the value for search: "))
k = 0 # To keep a track of index of the array elements for printing the index
for i in vals: # i is taking on element values
    if i == ele:
        print(k)
        break
    k += 1

Enter the value for search: 6
1


In [53]:
# searching array element automatically using an inbuilt function and returning the index value.
ele = int(input("Enter the value for search: "))
print(vals.index(ele))

Enter the value for search: 2


ValueError: array.index(x): x not in array

In [54]:
# searching array element automatically using an inbuilt function and returning the index value.
ele = int(input("Enter the value for search: "))
print(vals.index(ele))

Enter the value for search: 6
1


In [55]:
# Types of array Single Dimensional and Multi-Dimensional.
# Eg, 1D or 2D or 3D. 2D array is used to represent a matrix
# array package in python doesn't have multi-dimensional arrays. Eg:
arr = array('i',[1,2,3],[2,5,4]) # One pair of brackets is one row.

TypeError: array() takes at most 2 arguments (3 given)

In [63]:
# numpy - a third party package allows us to use multi-d array and do scientific calculations also.
# first example is using a single-d array when we have numpy

In [57]:
from numpy import *
arr = array('i',[1,2,2,5,4])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [58]:
arr = array([1,2,2,5,4])

In [59]:
print(arr)

[1 2 2 5 4]


In [60]:
# In numpy arrays typecode is not necessary. Using it eg:

In [61]:
arr = array([1,2,2,5,4],int)

In [62]:
print(arr)

[1 2 2 5 4]


In [64]:
# 6 ways to create an array in numpy: array(), linspace(), logspace(), arange(), zeros(), ones()

In [65]:
# array() used above and here.
print(arr.dtype) # Tells the type of the values in the array

int32


In [66]:
# when we don't give the type it guess the type and converts/stores the values accordingly.

In [69]:
# All the values entered were integers so it said I'll take int32 but next eg if anyone value is float with others integers and an array has same type of values, so all the int values are converted to float.

In [68]:
arr = array([1,2,2,5,4.0])
print(arr.dtype)
print(arr)

float64
[1. 2. 2. 5. 4.]


In [70]:
# Implicit Conversion

In [71]:
arr = array([1,2,2,5,4],int)
print(arr.dtype)
print(arr)

int32
[1 2 2 5 4]


In [72]:
arr = array([1,2,2,5,4],float)
print(arr.dtype)
print(arr)

float64
[1. 2. 2. 5. 4.]


In [73]:
# When you type float even if you entered int, it will convert them into float

In [74]:
arr = linspace(0,15,16) # it takes 3 para: start,stop and step. Similar to range. Stop in range is excluded but here it is included. 
# And the step here is not the step. It means the number of parts I wanna go =. Here for eg as from 0 to 16 there are 16 values.
# so it'll break the range into 16 diff equal parts.

In [75]:
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [76]:
# Float values as dividing into parts may give float so it always assume the values as floats.

In [78]:
arr = linspace(0,15,20)
print(arr)

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [79]:
arr = linspace(0,15) # default is 50 parts
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [81]:
arr = arange(1,15,2) # Same as range, so not parts but steps: 3rd para and 15 excluded
print(arr)

[ 1  3  5  7  9 11 13]


In [82]:
# in both linspace and logspace we create parts (break down the range into a number of parts) but the difference is that
# in linspace the gap between any 2 consecutive elements is fixed. In logspace for eg:
arr = logspace(1,40,5) # Number of parts is 5, the difference between any 2 consecutive numbers will be dependent upon the log of it.
# So it'll start from 10^1 to 10^40 and it'll be divided into 5 parts.
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [84]:
# If I wanna print after point with 2 decimal places
print('%.2f' %arr[0])

10.00


In [87]:
print('%.2f' %arr[4]) # arround 10 to the power 40

10000000000000000303786028427003666890752.00


In [89]:
# Creating an array of size 10 and by default all values = 0 or 1
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [90]:
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [91]:
# Floats above, for int below:
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [92]:
# Some operations in arrays:

In [93]:
arr = array([1,2,3,4,5])

In [94]:
# Adding 5 to each array element:
# one manual way is to iterate in a loop and add the values 5 to each element
# automatic way:
arr = arr + 5

In [95]:
print(arr)

[ 6  7  8  9 10]


In [97]:
# Adding 2 arrays: # Also known as vectorized operation
arr1 = array([1,2,3,4,5])
arr2 = array([6,1,9,3,2])
arr3 = arr1 + arr2
print(arr3)

[ 7  3 12  7  7]


In [99]:
# numpy num stands for numerical so maths operations are here trigo - sin, cos etc
# Example: Finding sin of the array
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [100]:
print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [101]:
print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [102]:
print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [103]:
print(sum(arr1))

15


In [104]:
print(min(arr1))

1


In [105]:
print(max(arr1))

5


In [109]:
# Can also find the unique element. Sort also
# Concatenating 2 arrays:
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6 1 9 3 2]


In [110]:
# Copying an array to another array
arr = arr1
print(arr)

[1 2 3 4 5]


In [111]:
print(arr1)

[1 2 3 4 5]


In [112]:
# In memory we still have only one array
id(arr)

2720553888816

In [113]:
id(arr1)

2720553888816

In [114]:
# Both are variables are pointing to the same array or the same memory address. This is also called aliasing as we're creating new alias for the same array
# We can modify the array (same array will get modified as they're alias) using any of the alias, arr1 or arr

In [132]:
# creating a new array at a different location/address - not an alias:
arr = arr1.view() # Shallow Copy

In [116]:
id(arr)

2720553888624

In [117]:
id(arr1)

2720553888816

In [118]:
print(arr)

[1 2 3 4 5]


In [119]:
print(arr1)

[1 2 3 4 5]


In [123]:
# There is still a problem here. We have 2 different types of copying. In Shallow Copy: It'll copy the elements but both the
# array elements are still dependent on each other, i.e., (both ways)changing/modifying anyone array element also modified the other array element.

In [121]:
arr[0]=9

In [122]:
print(arr1)

[9 2 3 4 5]


In [133]:
# In Deep Copy: 2 different copies of the array not related to each other in any way:
arr = arr1.copy()

In [125]:
print(arr1)

[9 2 3 4 5]


In [126]:
print(arr)

[9 2 3 4 5]


In [127]:
arr1[0]=1

In [128]:
print(arr1)

[1 2 3 4 5]


In [129]:
print(arr)

[9 2 3 4 5]


In [130]:
id(arr)

2720553889680

In [131]:
id(arr1)

2720553888816

In [134]:
# Multi-Dimensional Arrays:

In [135]:
# 2D Arrays:

In [136]:
arr1 = array([[1,2,3],[4,5,6]])

In [137]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [138]:
print(arr1.dtype)

int32


In [140]:
print(arr1.ndim) # Ranking = Number of Dimensions of an array it gives.

2


In [142]:
print(arr1.shape) # It gives you the number of rows and columns.

(2, 3)


In [143]:
print(arr1.size) # Size = rows x columns

6


In [145]:
# I wanna create a 1D array with the help of a 2D Array. Multi-d to Single-d
arr2 = arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


In [146]:
arr1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
# Example: Single-d to Multi-d array.
# 1D to 2D Example:
arr3 = arr2.reshape(3,4) # Passing the number of rows and columns I want in my 2D array

ValueError: cannot reshape array of size 6 into shape (3,4)

In [148]:
arr1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
arr2 = arr1.flatten()
# Example: Single-d to Multi-d array.
# 1D to 2D Example:
arr3 = arr2.reshape(3,4) # Passing the number of rows and columns I want in my 2D array
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [153]:
arr1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
arr2 = arr1.flatten()
# Example: Single-d to Multi-d array.
# 1D to 3D Example:
arr3 = arr2.reshape(2,2,3) # Passing the number of depth and rows and columns I want in my 3D array
print(arr3) # arr3 is a (big) 3D array containing 2 2D Arrays

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [156]:
# Row matrix and column matrix can be represented using 1D Arrays only. (1 row many columns or 1 column many rows)
# 2D Arrays with multiple rows and columns
arr1 = array([[1,2,3,6],[4,5,6,7]])
print(arr1)

[[1 2 3 6]
 [4 5 6 7]]


In [157]:
# Convert this 2D Array into a Matrix Format:
m = matrix(arr1)
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [158]:
# Output looks same but with this m we can perform matrix operations also

In [159]:
# Other ways of creating a matrix other than from an array: from a string or user input
m = matrix('1 2 3 6 ; 4 5 6 7') # Semi colon separates the rows
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [161]:
# eg 4 rows and 2 columns
m = matrix('1 2; 3 6 ; 4 5; 6 7') # Semi colon separates the rows and space separates the elements
print(m)

[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [162]:
m = matrix('1 2 3 ; 6 4 5 ; 1 6 7') # Semi colon separates the rows and space separates the elements
print(m)

[[1 2 3]
 [6 4 5]
 [1 6 7]]


In [163]:
diagonal(m)

array([1, 4, 7])

In [164]:
print(diagonal(m))

[1 4 7]


In [165]:
print(m.min())

1


In [166]:
print(m.max())

7


In [167]:
# Operations which we do with arrays can be done with matrices as well

In [168]:
# Addition, Multiplication of 2 matrices:
m1 = matrix('1 2 3 ; 6 4 5 ; 1 6 7')
m2 = matrix('1 2 3 ; 6 8 5 ; 2 6 7')
m3 = m1 + m2
print(m3)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [169]:
m3 = m1 * m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
